### ISSUE TITLE
idea for api (stronger)

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/request-generator#2]
```js
const requestGenerator = require('request-generator')
const gen = requestGenerator('google.com', 'item.*', (data) => {}, (err, next, req) => {})
 // gen is an async iterator

```

**Comment by jimdebeer** [comment]
where next is a method that you can call to redo the current generator OR pass new arguments -- req is the parsed request object

**Comment by marcusbesjes** [comment]
>  to redo the current generator

do you mean 
a. "to continue the generator, doing another request and continue to yield chunks from the new response"? / AKA next page
b. "to restart the generator,  / AKA next cycle / start again from page 1

**Comment by jimdebeer** [comment]
@youzi idea is fresh, will do it like this

**Comment by marcusbesjes** [comment]
@jimdebeer @youzi this way we are missing the ability to do all page requests in parallel (e.g. you know I'm going to do 10 requests with 20 per page) though, which is pretty nice to be able to do

**Comment by jimdebeer** [comment]
i would just make an extra funciton for that sets each page in a for loop

**Comment by jimdebeer** [comment]
```js
 
  for (let i = 0; i < 100; i++) {
    struct.set(requestGenerator(i))
  }

```

like this

**Comment by jimdebeer** [comment]
or with promises

**Comment by marcusbesjes** [comment]
I think that would cover it yes. Ok I'm going to modify the mvp with this.
